language: node_js
node_js:
- 10
env:
  global:
    secure: zRizzFmV+qzv50ipDrSHEk0i7YfR6mmxprWz9dFQjLNx2ns8rvFvz5L+h5gtfJG39dAXDxzKDcsj11P5ii5Sst7jqPsJ0t00bGrDliJntE6E0LJjmHMqcz1JMqjGI1xTfITCNoSQDeeC5rh2VMO4e9SKr+WdcZFp/XekSlbG1b8gEbBTNtoErvjB9FbIu1hGqRdvvLF+prHNLxjop1vFDVWL+Qkahqem+fQSbGH++ExLUeuu4iLq5hnvmeaY9XydrqlDNh2p/vzYtpqE6QZmm9fNgBT9FFK0Si9bcKaBfx1L0414HBWrbla4Iw2qppxfGyverh4Kx7g/YzhM3n7i5k5LBHPNC6WqxAgML/2aRW7JiG3sfo+X+CLQSxlVLhSQ3CE6hKZHMffLku1MrSLK+f8f/YjlN68Lp7W/1P3EUpm3qnaaduyd2xRmlz37tFCZ++37h5VkQRcx0+ARzJ9rAb3IQ0Lpe1uiCf2ZWXWkDaK+IKFUIFnqQsOsxl3/4IVzhq9OZxE1AuMvKb632jqos7HXfj9EhDRg+i6QPgCla0+URWZeExS9liXJJ61To2SN/iSCDc49CogainSaWGz1TvifxU5V8C0+wqeoGTsy/v6HAzlO3rV2DQIn4LP4KEFYLtrEYLOVaNB5dwbQXjUtRKrwE/reKjFb8/FK7XZIFUs=
before_deploy: npm run make-package && cd package
deploy:
  provider: npm
  email: ConnectedTV-Development@lists.forge.bbc.co.uk
  api_key:
    secure: iJuf8D/K3fEnesy7i8PoQh/auS6rRtixOo1kQCL+AhoF1KUym1HisbXvOxX4+oMJIj+g/23V/yvBPxRZb4JEbZEJAbGiqVnOHC6Uw/2faHr0YK4VAsRRb1++5362mqQg7ovFyl8FfPDgTIMc/23C9Ei5oDKnCwP95kq9/vRli9s61vuI0Ahm7rJ5NKGUOGQIPL5B4MYwPfy7LGw56MAp7loIXH+c/q2YlRiYt18iQ1KPISTe01OBDXz9B8lzCGE4IADiXZQqiZelE01Svk5NUF7b0shi3l1u5knmV4iEptwOqAT9Dgv7RbFwmT1hvIXQ5SjKwIWQFHpgB/sEeyEkB6wm/lYwBJhbgmp0Z26iSpjJHPHaNn8+tFo09Gntn2W6NTmqvlgegkTwVwVd+bvrP9t6T6OC5I9UkAvM7qCaSLcI5b0V4MsllKhQywslhiCD8hczgxVGJUf8LpLTx/PWwkJcdmCO1xgzwFNMe5UHQ3T0RJZAHVyfKw225CIk6k4TILmMJKyR268/CAtWpewT+Vq5VHjBlOSGcbJUoF/OitqZR7/d3zJL56+0VutrQAyIDgDJ5KIuRJgVqj7OhPbkQrtqMqF8qYAvZo0lBGVeR+vsVsA+sUmAPkTOe3k2FcH5GXoDYoj+Unrlwu4/aIGJc2dLvK22kwqIwYzr9z4Idpg=
  skip_cleanup: true
  on:
    tags: true
    repo: bbc/morty-docs
    branch: master
