language: node_js
node_js:
- 10
env:
  global:
    secure: zRizzFmV+qzv50ipDrSHEk0i7YfR6mmxprWz9dFQjLNx2ns8rvFvz5L+h5gtfJG39dAXDxzKDcsj11P5ii5Sst7jqPsJ0t00bGrDliJntE6E0LJjmHMqcz1JMqjGI1xTfITCNoSQDeeC5rh2VMO4e9SKr+WdcZFp/XekSlbG1b8gEbBTNtoErvjB9FbIu1hGqRdvvLF+prHNLxjop1vFDVWL+Qkahqem+fQSbGH++ExLUeuu4iLq5hnvmeaY9XydrqlDNh2p/vzYtpqE6QZmm9fNgBT9FFK0Si9bcKaBfx1L0414HBWrbla4Iw2qppxfGyverh4Kx7g/YzhM3n7i5k5LBHPNC6WqxAgML/2aRW7JiG3sfo+X+CLQSxlVLhSQ3CE6hKZHMffLku1MrSLK+f8f/YjlN68Lp7W/1P3EUpm3qnaaduyd2xRmlz37tFCZ++37h5VkQRcx0+ARzJ9rAb3IQ0Lpe1uiCf2ZWXWkDaK+IKFUIFnqQsOsxl3/4IVzhq9OZxE1AuMvKb632jqos7HXfj9EhDRg+i6QPgCla0+URWZeExS9liXJJ61To2SN/iSCDc49CogainSaWGz1TvifxU5V8C0+wqeoGTsy/v6HAzlO3rV2DQIn4LP4KEFYLtrEYLOVaNB5dwbQXjUtRKrwE/reKjFb8/FK7XZIFUs=
